image: gitpod/workspace-full:latest

tasks:
  - command: |
      nvm install lts/*
      npm install -g npm
      npm install --location=global @cloudflare/wrangler

vscode:
  extensions:
    - ms-azuretools.vscode-docker
    - bungcip.better-toml
    - zamerick.vscode-caddyfile-syntax
    - EditorConfig.EditorConfig
    - GitHub.vscode-pull-request-github
    - GitHub.github-vscode-theme
    - bierner.github-markdown-preview
    - bierner.markdown-checkbox
    - bierner.markdown-emoji
    - bierner.markdown-footnotes
    - bierner.markdown-mermaid
    - bierner.markdown-preview-github-styles
    - bierner.markdown-yaml-preamble
    - Gruntfuggly.todo-tree
    - WakaTime.vscode-wakatime
    - timonwong.shellcheck
    - GitLab.gitlab-workflow
    - PKief.markdown-checkbox
    - PKief.material-icon-theme
    - PKief.material-product-icons
    - ms-python.python
    - rebornix.ruby
    - golang.go
    - silvenon.mdx
    - DavidAnson.vscode-markdownlint
    - abumalick.vscode-nvm
    - amazonwebservices.aws-toolkit-vscode
    - arcticicestudio.nord-visual-studio-code

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: true
    addComment: true
    addBadge: true
    addLabel: true
