name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 */12 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@master
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          base_indepth: true
          base: header, activity, community, repositories, metadata, wakatime, tweets, anilist
          repositories_forks: true
          repositories_batch: 300
          config_twemoji: true
          config_octicon: true
          plugin_wakatime: true
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}
          plugin_wakatime_user: tigefa
          plugin_wakatime_days: 365
          plugin_wakatime_languages_other: true
          plugin_traffic: true
          plugin_tweets: true
          plugin_tweets_token: ${{ secrets.TWITTER_TOKEN }}
          plugin_tweets_user: sugengtigefa
          plugin_tweets_limit: 1
          plugin_anilist: true
          plugin_anilist_medias: anime
          plugin_anilist_sections: favorites, watching
          plugin_anilist_user: tigefa
          plugin_anilist_limit: 1
