name: Metrics
on:
  # Schedule daily updates
  schedule: [{cron: "0 */12 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          config_timezone: Asia/Jakarta
          config_display: large
          use_prebuilt_image: yes
          optimize: svg
          experimental_features: --optimize-svg
          base_indepth: true
          base: header, repositories
          config_order: base.header, base.repositories, wakatime, anilist
          repositories_forks: true
          repositories_batch: 300
          config_twemoji: true
          config_octicon: true
          plugin_wakatime: true
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}
          plugin_wakatime_user: tigefa
          plugin_wakatime_days: 365
          plugin_wakatime_languages_other: true
          plugin_traffic: true
          plugin_anilist: true
          plugin_anilist_medias: anime
          plugin_anilist_sections: favorites, watching, characters
          plugin_anilist_user: tigefa
          plugin_anilist_limit: 1
